### ISSUE TITLE
ENOENT: no such file or directory

### ISSUE THREAD

**Issue by dkelosky** [zowe/zowe-cli-zos-make-plugin#2]
![image](https://user-images.githubusercontent.com/14940561/64352333-dc206f00-cfc9-11e9-84ad-b91007364a52.png)

**Comment by tucker01** [comment]
Oops, forgot to add the samples to the files in package.json. Thanks

**Comment by tucker01** [comment]
OK. It should be good to go. I actually tried it this time haha

**Comment by dkelosky** [comment]
thanks - it works now. I had to delete some residual files first.

**Comment by tucker01** [comment]
Awesome, thanks for verifying so fast.
